In [3]:
!pip install numpy

In [4]:
import numpy as np
import pandas as pd

In [5]:
add=pd.read_csv("Additional.csv")
add

Date Sales Rep Customer Code  Sales  Profit Region
0     4-Jan-08     Abhay    CUSTN 1014  10600    4080  South
1     5-Jan-08  Jaspreet    CUSTN 1011  11250    4880   East
2     6-Jan-08     Abhay    CUSTN 1011  13050    2780  South
3     6-Jan-08    Varsha    CUSTN 1018  14950    5620   West
4     7-Jan-08     Bruce    CUSTN 1022  14200    5320   East
..         ...       ...           ...    ...     ...    ...
96   22-Jun-08  Veronica    CUSTN 1015  11050    3120   West
97   24-Jun-08   Anshika    CUSTN 1014  13050    4940  South
98   28-Jun-08     Rajat    CUSTN 1021  11650    3240  North
99   30-Jun-08     Bruce    CUSTN 1017  10150    2400   West
100   1-Jul-08    Varsha    CUSTN 1013  13150    4080  North

[101 rows x 6 columns]

In [6]:
add.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Date           101 non-null    object
 1   Sales Rep      101 non-null    object
 2   Customer Code  101 non-null    object
 3   Sales          101 non-null    int64 
 4   Profit         101 non-null    int64 
 5   Region         101 non-null    object
dtypes: int64(2), object(4)
memory usage: 4.9+ KB


In [7]:
add.isnull().any()

Date             False
Sales Rep        False
Customer Code    False
Sales            False
Profit           False
Region           False
dtype: bool

In [8]:
add.isnull().sum()

Date             0
Sales Rep        0
Customer Code    0
Sales            0
Profit           0
Region           0
dtype: int64

In [9]:
add.describe()

Sales       Profit
count    101.000000   101.000000
mean   12583.168317  3842.376238
std     1414.571971  1186.559015
min    10100.000000  2000.000000
25%    11650.000000  2800.000000
50%    12450.000000  3720.000000
75%    13750.000000  4940.000000
max    15000.000000  5800.000000

In [10]:
add.shape

(101, 6)

In [11]:
add.size

606

In [12]:
add.ndim

2

In [13]:
lst=[1,2,3,4,5,6]
lst

[1, 2, 3, 4, 5, 6]

In [14]:
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
arr1=arr.reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2=np.arange(0,10,2)
arr2

array([0, 2, 4, 6, 8])

In [17]:
arr3=np.array([[1,2,2,3,5,6,2,0,9,4]])
arr4=np.sort(arr3)
arr4

array([[0, 1, 2, 2, 2, 3, 4, 5, 6, 9]])

In [18]:
arr4=np.unique(arr3)
arr4

array([0, 1, 2, 3, 4, 5, 6, 9])

In [19]:
arr4=np.hsplit(arr3,5)
arr4

[array([[1, 2]]),
 array([[2, 3]]),
 array([[5, 6]]),
 array([[2, 0]]),
 array([[9, 4]])]

In [20]:
arr5=np.vsplit(arr3,1)
arr5

[array([[1, 2, 2, 3, 5, 6, 2, 0, 9, 4]])]

In [21]:
arr6=np.vstack((arr3,arr3))
arr6

array([[1, 2, 2, 3, 5, 6, 2, 0, 9, 4],
       [1, 2, 2, 3, 5, 6, 2, 0, 9, 4]])

In [22]:
arr6=np.hstack((arr3,arr3))
arr6

array([[1, 2, 2, 3, 5, 6, 2, 0, 9, 4, 1, 2, 2, 3, 5, 6, 2, 0, 9, 4]])

In [23]:
arr7=np.transpose(arr3)
arr7

array([[1],
       [2],
       [2],
       [3],
       [5],
       [6],
       [2],
       [0],
       [9],
       [4]])

In [24]:
arr8=np.flip(arr3)
arr8

array([[4, 9, 0, 2, 6, 5, 3, 2, 2, 1]])

In [25]:
arr3.flatten()

array([1, 2, 2, 3, 5, 6, 2, 0, 9, 4])

In [26]:
arr3.ravel()

array([1, 2, 2, 3, 5, 6, 2, 0, 9, 4])

In [27]:
from numpy import random

In [28]:
arr9=np.random.randint(10,size=(2,2))
arr9

array([[4, 9],
       [6, 0]])

In [29]:
arr9=np.random.rand(10)
arr9

array([0.13131241, 0.85982281, 0.66042143, 0.73130589, 0.48793223,
       0.56380289, 0.26864069, 0.16018712, 0.61635307, 0.29136123])

In [30]:
arr=np.array([1,2,4,5,3])
arr=np.random.permutation(arr)
arr

array([2, 4, 1, 3, 5])

In [31]:
arr=np.random.shuffle(arr3)
arr3

array([[1, 2, 2, 3, 5, 6, 2, 0, 9, 4]])

In [32]:
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
arr3=np.dot(arr1,arr2)
arr3

80

In [33]:
arr5=arr3[np.newaxis]
arr5

array([80])

In [34]:
ar=([[6,2,3,4],[1,22,10,0]])
ar

[[6, 2, 3, 4], [1, 22, 10, 0]]

In [37]:
add.head()

Date Sales Rep Customer Code  Sales  Profit Region
0  4-Jan-08     Abhay    CUSTN 1014  10600    4080  South
1  5-Jan-08  Jaspreet    CUSTN 1011  11250    4880   East
2  6-Jan-08     Abhay    CUSTN 1011  13050    2780  South
3  6-Jan-08    Varsha    CUSTN 1018  14950    5620   West
4  7-Jan-08     Bruce    CUSTN 1022  14200    5320   East

In [74]:
add.drop(["Date"],axis=1,inplace=True)

In [76]:
add

Sales Rep Customer Code  Sales  Profit Region
0       Abhay    CUSTN 1014  10600    4080  South
1    Jaspreet    CUSTN 1011  11250    4880   East
2       Abhay    CUSTN 1011  13050    2780  South
3      Varsha    CUSTN 1018  14950    5620   West
4       Bruce    CUSTN 1022  14200    5320   East
..        ...           ...    ...     ...    ...
96   Veronica    CUSTN 1015  11050    3120   West
97    Anshika    CUSTN 1014  13050    4940  South
98      Rajat    CUSTN 1021  11650    3240  North
99      Bruce    CUSTN 1017  10150    2400   West
100    Varsha    CUSTN 1013  13150    4080  North

[101 rows x 5 columns]

In [78]:
add.drop(add.index[1:4],axis=0,inplace=True)

In [80]:
add

Sales Rep Customer Code  Sales  Profit Region
0       Abhay    CUSTN 1014  10600    4080  South
4       Bruce    CUSTN 1022  14200    5320   East
5       Abhay    CUSTN 1011  10900    3380   East
6    Jaspreet    CUSTN 1015  10200    4420   East
7    Veronica    CUSTN 1011  10100    2720  North
..        ...           ...    ...     ...    ...
96   Veronica    CUSTN 1015  11050    3120   West
97    Anshika    CUSTN 1014  13050    4940  South
98      Rajat    CUSTN 1021  11650    3240  North
99      Bruce    CUSTN 1017  10150    2400   West
100    Varsha    CUSTN 1013  13150    4080  North

[98 rows x 5 columns]

In [82]:
data=pd.read_csv("data.csv")
data

Date Sales Rep Customer Code  Sales  Profit Region
0    30-May-05      Mark    CUSTN 1019  14900    5480  North
1    31-May-05     Rajat    CUSTN 1011  12400    2540  South
2     5-Jun-05     Rajat    CUSTN 1012  14150    4540  South
3     7-Jun-05     Abhay    CUSTN 1016  11100    3780  South
4     9-Jun-05     Rajat    CUSTN 1018  12650    3960   East
..         ...       ...           ...    ...     ...    ...
484  20-Dec-07   Charley    CUSTN 1013  10450    4600   West
485  25-Dec-07   Charley    CUSTN 1018  10400    2940  South
486  25-Dec-07  Veronica    CUSTN 1022  12350    2620  North
487  27-Dec-07   Charley    CUSTN 1013  13800    4880  North
488  27-Dec-07     Bruce    CUSTN 1014  11200    5640   East

[489 rows x 6 columns]

In [88]:
merge=pd.concat((add,data),axis=0)
merge

Sales Rep Customer Code  Sales  Profit Region       Date
0       Abhay    CUSTN 1014  10600    4080  South        NaN
4       Bruce    CUSTN 1022  14200    5320   East        NaN
5       Abhay    CUSTN 1011  10900    3380   East        NaN
6    Jaspreet    CUSTN 1015  10200    4420   East        NaN
7    Veronica    CUSTN 1011  10100    2720  North        NaN
..        ...           ...    ...     ...    ...        ...
484   Charley    CUSTN 1013  10450    4600   West  20-Dec-07
485   Charley    CUSTN 1018  10400    2940  South  25-Dec-07
486  Veronica    CUSTN 1022  12350    2620  North  25-Dec-07
487   Charley    CUSTN 1013  13800    4880  North  27-Dec-07
488     Bruce    CUSTN 1014  11200    5640   East  27-Dec-07

[587 rows x 6 columns]

In [90]:
cust=pd.read_csv("customers.csv")
cust

Customer Customer Code Association Date
0    Shyam & Sharma Co    CUSTN 1011        23-Jun-05
1                 MNTL    CUSTN 1012         4-Aug-05
2          Sharma & Co    CUSTN 1013         9-Jun-05
3     White Associates    CUSTN 1014        28-Jul-05
4   Boston Consultants    CUSTN 1015         1-Jul-05
5      Shah Associates    CUSTN 1016        11-Jul-05
6   Namint Enterprises    CUSTN 1017         5-Jun-05
7         Data Tronics    CUSTN 1018        22-Aug-05
8                  VCC    CUSTN 1019        11-Aug-05
9       India Trotters    CUSTN 1020         3-Sep-05
10            Good Fly    CUSTN 1021        13-Jun-05
11  Jindle Power Works    CUSTN 1022         7-Aug-05

In [100]:
sample=pd.merge(merge,cust,on="Customer Code",how="inner")
sample

Sales Rep Customer Code  Sales  Profit Region       Date  \
0       Abhay    CUSTN 1014  10600    4080  South        NaN   
1       Bruce    CUSTN 1022  14200    5320   East        NaN   
2       Abhay    CUSTN 1011  10900    3380   East        NaN   
3    Jaspreet    CUSTN 1015  10200    4420   East        NaN   
4    Veronica    CUSTN 1011  10100    2720  North        NaN   
..        ...           ...    ...     ...    ...        ...   
582   Charley    CUSTN 1013  10450    4600   West  20-Dec-07   
583   Charley    CUSTN 1018  10400    2940  South  25-Dec-07   
584  Veronica    CUSTN 1022  12350    2620  North  25-Dec-07   
585   Charley    CUSTN 1013  13800    4880  North  27-Dec-07   
586     Bruce    CUSTN 1014  11200    5640   East  27-Dec-07   

               Customer Association Date  
0      White Associates        28-Jul-05  
1    Jindle Power Works         7-Aug-05  
2     Shyam & Sharma Co        23-Jun-05  
3    Boston Consultants         1-Jul-05  
4     Shyam & Sharma Co        23-Jun-05  
..                  ...              ...  
582         Sharma & Co         9-Jun-05  
583        Data Tronics        22-Aug-05  
584  Jindle Power Works         7-Aug-05  
585         Sharma & Co         9-Jun-05  
586    White Associates        28-Jul-05  

[587 rows x 8 columns]

In [106]:
sample["Sales Rep"].duplicated().sum()

575

In [108]:
sample["Sales Rep"].drop_duplicates(inplace=True)

In [112]:
sample["Sales Rep"]

0         Abhay
1         Bruce
2         Abhay
3      Jaspreet
4      Veronica
         ...   
582     Charley
583     Charley
584    Veronica
585     Charley
586       Bruce
Name: Sales Rep, Length: 587, dtype: object